<?php

namespace Database\Seeders;

use App\Models\Spell;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SpellSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Spell::factory()->create(['name' => "Acid Splash", 'level' => 0]);
        Spell::factory()->create(['name' => "Aid", 'level' => 2]);
        Spell::factory()->create(['name' => "Alarm", 'level' => 1]);
        Spell::factory()->create(['name' => "Alter Self", 'level' => 2]);
        Spell::factory()->create(['name' => "Animal Friendship", 'level' => 1]);
        Spell::factory()->create(['name' => "Animal Messenger", 'level' => 2]);
        Spell::factory()->create(['name' => "Animal Shapes", 'level' => 8]);
        Spell::factory()->create(['name' => "Animate Dead", 'level' => 3]);
        Spell::factory()->create(['name' => "Animate Objects", 'level' => 5]);
        Spell::factory()->create(['name' => "Antilife Shell", 'level' => 5]);
        Spell::factory()->create(['name' => "Antimagic Field", 'level' => 8]);
        Spell::factory()->create(['name' => "Antipathy/Sympathy", 'level' => 8]);
        Spell::factory()->create(['name' => "Arcane Eye", 'level' => 4]);
        Spell::factory()->create(['name' => "Arcane Gate", 'level' => 6]);
        Spell::factory()->create(['name' => "Arcane Lock", 'level' => 2]);
        Spell::factory()->create(['name' => "Arcane Vigor", 'level' => 2]);
        Spell::factory()->create(['name' => "Armor of Agathys", 'level' => 1]);
        Spell::factory()->create(['name' => "Arms of Hadar", 'level' => 1]);
        Spell::factory()->create(['name' => "Astral Projection", 'level' => 9]);
        Spell::factory()->create(['name' => "Augury", 'level' => 2]);
        Spell::factory()->create(['name' => "Aura of Life", 'level' => 4]);
        Spell::factory()->create(['name' => "Aura of Purity", 'level' => 4]);
        Spell::factory()->create(['name' => "Aura of Vitality", 'level' => 3]);
        Spell::factory()->create(['name' => "Awaken", 'level' => 5]);
        Spell::factory()->create(['name' => "Bane", 'level' => 1]);
        Spell::factory()->create(['name' => "Banishing Smite", 'level' => 5]);
        Spell::factory()->create(['name' => "Banishment", 'level' => 4]);
        Spell::factory()->create(['name' => "Barkskin", 'level' => 2]);
        Spell::factory()->create(['name' => "Beacon of Hope", 'level' => 3]);
        Spell::factory()->create(['name' => "Beast Sense", 'level' => 2]);
        Spell::factory()->create(['name' => "Befuddlement", 'level' => 8]);
        Spell::factory()->create(['name' => "Bestow Curse", 'level' => 3]);
        Spell::factory()->create(['name' => "Bigby's Hand", 'level' => 5]);
        Spell::factory()->create(['name' => "Blade Barrier", 'level' => 6]);
        Spell::factory()->create(['name' => "Blade Ward", 'level' => 0]);
        Spell::factory()->create(['name' => "Bless", 'level' => 1]);
        Spell::factory()->create(['name' => "Blight", 'level' => 4]);
        Spell::factory()->create(['name' => "Blinding Smite", 'level' => 3]);
        Spell::factory()->create(['name' => "Blindness/Deafness", 'level' => 2]);
        Spell::factory()->create(['name' => "Blink", 'level' => 3]);
        Spell::factory()->create(['name' => "Blur", 'level' => 2]);
        Spell::factory()->create(['name' => "Burning Hands", 'level' => 1]);
        Spell::factory()->create(['name' => "Call Lightning", 'level' => 3]);
        Spell::factory()->create(['name' => "Calm Emotions", 'level' => 2]);
        Spell::factory()->create(['name' => "Chain Lightning", 'level' => 6]);
        Spell::factory()->create(['name' => "Charm Monster", 'level' => 4]);
        Spell::factory()->create(['name' => "Charm Person", 'level' => 1]);
        Spell::factory()->create(['name' => "Chill Touch", 'level' => 0]);
        Spell::factory()->create(['name' => "Chromatic Orb", 'level' => 1]);
        Spell::factory()->create(['name' => "Circle of Death", 'level' => 6]);
        Spell::factory()->create(['name' => "Circle of Power", 'level' => 5]);
        Spell::factory()->create(['name' => "Clairvoyance", 'level' => 3]);
        Spell::factory()->create(['name' => "Clone", 'level' => 8]);
        Spell::factory()->create(['name' => "Cloudkill", 'level' => 5]);
        Spell::factory()->create(['name' => "Cloud of Daggers", 'level' => 2]);
        Spell::factory()->create(['name' => "Color Spray", 'level' => 1]);
        Spell::factory()->create(['name' => "Command", 'level' => 1]);
        Spell::factory()->create(['name' => "Commune", 'level' => 5]);
        Spell::factory()->create(['name' => "Commune with Nature", 'level' => 5]);
        Spell::factory()->create(['name' => "Compelled Duel", 'level' => 1]);
        Spell::factory()->create(['name' => "Comprehend Languages", 'level' => 1]);
        Spell::factory()->create(['name' => "Compulsion", 'level' => 4]);
        Spell::factory()->create(['name' => "Cone of Cold", 'level' => 5]);
        Spell::factory()->create(['name' => "Confusion", 'level' => 4]);
        Spell::factory()->create(['name' => "Conjure Animals", 'level' => 3]);
        Spell::factory()->create(['name' => "Conjure Barrage", 'level' => 3]);
        Spell::factory()->create(['name' => "Conjure Celestial", 'level' => 7]);
        Spell::factory()->create(['name' => "Conjure Elemental", 'level' => 5]);
        Spell::factory()->create(['name' => "Conjure Fey", 'level' => 6]);
        Spell::factory()->create(['name' => "Conjure Minor Elementals", 'level' => 4]);
        Spell::factory()->create(['name' => "Conjure Volley", 'level' => 5]);
        Spell::factory()->create(['name' => "Conjure Woodland Beings", 'level' => 4]);
        Spell::factory()->create(['name' => "Contact Other Plane", 'level' => 5]);
        Spell::factory()->create(['name' => "Contagion", 'level' => 5]);
        Spell::factory()->create(['name' => "Contingency", 'level' => 6]);
        Spell::factory()->create(['name' => "Continual Flame", 'level' => 2]);
        Spell::factory()->create(['name' => "Control Water", 'level' => 4]);
        Spell::factory()->create(['name' => "Control Weather", 'level' => 8]);
        Spell::factory()->create(['name' => "Cordon of Arrows", 'level' => 2]);
        Spell::factory()->create(['name' => "Counterspell", 'level' => 3]);
        Spell::factory()->create(['name' => "Create Food and Water", 'level' => 3]);
        Spell::factory()->create(['name' => "Create or Destroy Water", 'level' => 1]);
        Spell::factory()->create(['name' => "Create Undead", 'level' => 6]);
        Spell::factory()->create(['name' => "Creation", 'level' => 5]);
        Spell::factory()->create(['name' => "Crown of Madness", 'level' => 2]);
        Spell::factory()->create(['name' => "Crusader's Mantle", 'level' => 3]);
        Spell::factory()->create(['name' => "Cure Wounds", 'level' => 1]);
        Spell::factory()->create(['name' => "Dancing Lights", 'level' => 0]);
        Spell::factory()->create(['name' => "Darkness", 'level' => 2]);
        Spell::factory()->create(['name' => "Darkvision", 'level' => 2]);
        Spell::factory()->create(['name' => "Daylight", 'level' => 3]);
        Spell::factory()->create(['name' => "Death Ward", 'level' => 4]);
        Spell::factory()->create(['name' => "Delayed Blast Fireball", 'level' => 7]);
        Spell::factory()->create(['name' => "Demiplane", 'level' => 8]);
        Spell::factory()->create(['name' => "Destructive Wave", 'level' => 5]);
        Spell::factory()->create(['name' => "Detect Evil and Good", 'level' => 1]);
        Spell::factory()->create(['name' => "Detect Magic", 'level' => 1]);
        Spell::factory()->create(['name' => "Detect Poison and Disease", 'level' => 1]);
        Spell::factory()->create(['name' => "Detect Thoughts", 'level' => 2]);
        Spell::factory()->create(['name' => "Dimension Door", 'level' => 4]);
        Spell::factory()->create(['name' => "Disguise Self", 'level' => 1]);
        Spell::factory()->create(['name' => "Disintegrate", 'level' => 6]);
        Spell::factory()->create(['name' => "Dispel Evil and Good", 'level' => 5]);
        Spell::factory()->create(['name' => "Dispel Magic", 'level' => 3]);
        Spell::factory()->create(['name' => "Dissonant Whispers", 'level' => 1]);
        Spell::factory()->create(['name' => "Divination", 'level' => 4]);
        Spell::factory()->create(['name' => "Divine Favor", 'level' => 1]);
        Spell::factory()->create(['name' => "Divine Smite", 'level' => 1]);
        Spell::factory()->create(['name' => "Divine Word", 'level' => 7]);
        Spell::factory()->create(['name' => "Dominate Beast", 'level' => 4]);
        Spell::factory()->create(['name' => "Dominate Monster", 'level' => 8]);
        Spell::factory()->create(['name' => "Dominate Person", 'level' => 5]);
        Spell::factory()->create(['name' => "Dragon's Breath", 'level' => 2]);
        Spell::factory()->create(['name' => "Drawmij's Instant Summons", 'level' => 6]);
        Spell::factory()->create(['name' => "Dream", 'level' => 5]);
        Spell::factory()->create(['name' => "Druidcraft", 'level' => 0]);
        Spell::factory()->create(['name' => "Earthquake", 'level' => 8]);
        Spell::factory()->create(['name' => "Eldritch Blast", 'level' => 0]);
        Spell::factory()->create(['name' => "Elementalism", 'level' => 0]);
        Spell::factory()->create(['name' => "Elemental Weapon", 'level' => 3]);
        Spell::factory()->create(['name' => "Enhance Ability", 'level' => 2]);
        Spell::factory()->create(['name' => "Enlarge/Reduce", 'level' => 2]);
        Spell::factory()->create(['name' => "Ensnaring Strike", 'level' => 1]);
        Spell::factory()->create(['name' => "Entangle", 'level' => 1]);
        Spell::factory()->create(['name' => "Enthrall", 'level' => 2]);
        Spell::factory()->create(['name' => "Etherealness", 'level' => 7]);
        Spell::factory()->create(['name' => "Evard's Black Tentacles", 'level' => 4]);
        Spell::factory()->create(['name' => "Expeditious Retreat", 'level' => 1]);
        Spell::factory()->create(['name' => "Eyebite", 'level' => 6]);
        Spell::factory()->create(['name' => "Fabricate", 'level' => 4]);
        Spell::factory()->create(['name' => "Faerie Fire", 'level' => 1]);
        Spell::factory()->create(['name' => "False Life", 'level' => 1]);
        Spell::factory()->create(['name' => "Fear", 'level' => 3]);
        Spell::factory()->create(['name' => "Feather Fall", 'level' => 1]);
        Spell::factory()->create(['name' => "Feign Death", 'level' => 3]);
        Spell::factory()->create(['name' => "Find Familiar", 'level' => 1]);
        Spell::factory()->create(['name' => "Find Steed", 'level' => 2]);
        Spell::factory()->create(['name' => "Find the Path", 'level' => 6]);
        Spell::factory()->create(['name' => "Find Traps", 'level' => 2]);
        Spell::factory()->create(['name' => "Finger of Death", 'level' => 7]);
        Spell::factory()->create(['name' => "Fireball", 'level' => 3]);
        Spell::factory()->create(['name' => "Fire Bolt", 'level' => 0]);
        Spell::factory()->create(['name' => "Fire Shield", 'level' => 4]);
        Spell::factory()->create(['name' => "Fire Storm", 'level' => 7]);
        Spell::factory()->create(['name' => "Flame Blade", 'level' => 2]);
        Spell::factory()->create(['name' => "Flame Strike", 'level' => 5]);
        Spell::factory()->create(['name' => "Flaming Sphere", 'level' => 2]);
        Spell::factory()->create(['name' => "Flesh to Stone", 'level' => 6]);
        Spell::factory()->create(['name' => "Fly", 'level' => 3]);
        Spell::factory()->create(['name' => "Fog Cloud", 'level' => 1]);
        Spell::factory()->create(['name' => "Forbiddance", 'level' => 6]);
        Spell::factory()->create(['name' => "Forcecage", 'level' => 7]);
        Spell::factory()->create(['name' => "Foresight", 'level' => 9]);
        Spell::factory()->create(['name' => "Freedom of Movement", 'level' => 4]);
        Spell::factory()->create(['name' => "Friends", 'level' => 0]);
        Spell::factory()->create(['name' => "Gaseous Form", 'level' => 3]);
        Spell::factory()->create(['name' => "Gate", 'level' => 9]);
        Spell::factory()->create(['name' => "Geas", 'level' => 5]);
        Spell::factory()->create(['name' => "Gentle Repose", 'level' => 2]);
        Spell::factory()->create(['name' => "Giant Insect", 'level' => 4]);
        Spell::factory()->create(['name' => "Glibness", 'level' => 8]);
        Spell::factory()->create(['name' => "Globe of Invulnerability", 'level' => 6]);
        Spell::factory()->create(['name' => "Glyph of Warding", 'level' => 3]);
        Spell::factory()->create(['name' => "Goodberry", 'level' => 1]);
        Spell::factory()->create(['name' => "Grasping Vine", 'level' => 4]);
        Spell::factory()->create(['name' => "Grease", 'level' => 1]);
        Spell::factory()->create(['name' => "Greater Invisibility", 'level' => 4]);
        Spell::factory()->create(['name' => "Greater Restoration", 'level' => 5]);
        Spell::factory()->create(['name' => "Guardian of Faith", 'level' => 4]);
        Spell::factory()->create(['name' => "Guards and Wards", 'level' => 6]);
        Spell::factory()->create(['name' => "Guidance", 'level' => 0]);
        Spell::factory()->create(['name' => "Guiding Bolt", 'level' => 1]);
        Spell::factory()->create(['name' => "Gust of Wind", 'level' => 2]);
        Spell::factory()->create(['name' => "Hail of Thorns", 'level' => 1]);
        Spell::factory()->create(['name' => "Hallow", 'level' => 5]);
        Spell::factory()->create(['name' => "Hallucinatory Terrain", 'level' => 4]);
        Spell::factory()->create(['name' => "Harm", 'level' => 6]);
        Spell::factory()->create(['name' => "Haste", 'level' => 3]);
        Spell::factory()->create(['name' => "Heal", 'level' => 6]);
        Spell::factory()->create(['name' => "Healing Word", 'level' => 1]);
        Spell::factory()->create(['name' => "Heat Metal", 'level' => 2]);
        Spell::factory()->create(['name' => "Hellish Rebuke", 'level' => 1]);
        Spell::factory()->create(['name' => "Heroes' Feast", 'level' => 6]);
        Spell::factory()->create(['name' => "Heroism", 'level' => 1]);
        Spell::factory()->create(['name' => "Hex", 'level' => 1]);
        Spell::factory()->create(['name' => "Hold Monster", 'level' => 5]);
        Spell::factory()->create(['name' => "Hold Person", 'level' => 2]);
        Spell::factory()->create(['name' => "Holy Aura", 'level' => 8]);
        Spell::factory()->create(['name' => "Hunger of Hadar", 'level' => 3]);
        Spell::factory()->create(['name' => "Hunter's Mark", 'level' => 1]);
        Spell::factory()->create(['name' => "Hypnotic Pattern", 'level' => 3]);
        Spell::factory()->create(['name' => "Ice Knife", 'level' => 1]);
        Spell::factory()->create(['name' => "Ice Storm", 'level' => 4]);
        Spell::factory()->create(['name' => "Identify", 'level' => 1]);
        Spell::factory()->create(['name' => "Illusory Script", 'level' => 1]);
        Spell::factory()->create(['name' => "Imprisonment", 'level' => 9]);
        Spell::factory()->create(['name' => "Incendiary Cloud", 'level' => 8]);
        Spell::factory()->create(['name' => "Inflict Wounds", 'level' => 1]);
        Spell::factory()->create(['name' => "Insect Plague", 'level' => 5]);
        Spell::factory()->create(['name' => "Invisibility", 'level' => 2]);
        Spell::factory()->create(['name' => "Jallarzi's Storm of Radiance", 'level' => 5]);
        Spell::factory()->create(['name' => "Jump", 'level' => 1]);
        Spell::factory()->create(['name' => "Knock", 'level' => 2]);
        Spell::factory()->create(['name' => "Legend Lore", 'level' => 5]);
        Spell::factory()->create(['name' => "Leomund's Secret Chest", 'level' => 4]);
        Spell::factory()->create(['name' => "Leomund's Tiny Hut", 'level' => 3]);
        Spell::factory()->create(['name' => "Lesser Restoration", 'level' => 2]);
        Spell::factory()->create(['name' => "Levitate", 'level' => 2]);
        Spell::factory()->create(['name' => "Light", 'level' => 0]);
        Spell::factory()->create(['name' => "Lightning Arrow", 'level' => 3]);
        Spell::factory()->create(['name' => "Lightning Bolt", 'level' => 3]);
        Spell::factory()->create(['name' => "Locate Animals or Plants", 'level' => 2]);
        Spell::factory()->create(['name' => "Locate Creature", 'level' => 4]);
        Spell::factory()->create(['name' => "Locate Object", 'level' => 2]);
        Spell::factory()->create(['name' => "Longstrider", 'level' => 1]);
        Spell::factory()->create(['name' => "Mage Armor", 'level' => 1]);
        Spell::factory()->create(['name' => "Mage Hand", 'level' => 0]);
        Spell::factory()->create(['name' => "Magic Circle", 'level' => 3]);
        Spell::factory()->create(['name' => "Magic Jar", 'level' => 6]);
        Spell::factory()->create(['name' => "Magic Missile", 'level' => 1]);
        Spell::factory()->create(['name' => "Magic Mouth", 'level' => 2]);
        Spell::factory()->create(['name' => "Magic Weapon", 'level' => 2]);
        Spell::factory()->create(['name' => "Major Image", 'level' => 3]);
        Spell::factory()->create(['name' => "Mass Cure Wounds", 'level' => 5]);
        Spell::factory()->create(['name' => "Mass Heal", 'level' => 9]);
        Spell::factory()->create(['name' => "Mass Healing Word", 'level' => 3]);
        Spell::factory()->create(['name' => "Mass Suggestion", 'level' => 6]);
        Spell::factory()->create(['name' => "Maze", 'level' => 8]);
        Spell::factory()->create(['name' => "Meld into Stone", 'level' => 3]);
        Spell::factory()->create(['name' => "Melf's Acid Arrow", 'level' => 2]);
        Spell::factory()->create(['name' => "Mending", 'level' => 0]);
        Spell::factory()->create(['name' => "Message", 'level' => 0]);
        Spell::factory()->create(['name' => "Meteor Swarm", 'level' => 9]);
        Spell::factory()->create(['name' => "Mind Blank", 'level' => 8]);
        Spell::factory()->create(['name' => "Mind Sliver", 'level' => 0]);
        Spell::factory()->create(['name' => "Mind Spike", 'level' => 2]);
        Spell::factory()->create(['name' => "Minor Illusion", 'level' => 0]);
        Spell::factory()->create(['name' => "Mirage Arcane", 'level' => 7]);
        Spell::factory()->create(['name' => "Mirror Image", 'level' => 2]);
        Spell::factory()->create(['name' => "Mislead", 'level' => 5]);
        Spell::factory()->create(['name' => "Misty Step", 'level' => 2]);
        Spell::factory()->create(['name' => "Modify Memory", 'level' => 5]);
        Spell::factory()->create(['name' => "Moonbeam", 'level' => 2]);
        Spell::factory()->create(['name' => "Mordenkainen's Faithful Hound", 'level' => 4]);
        Spell::factory()->create(['name' => "Mordenkainen's Magnificent Mansion", 'level' => 7]);
        Spell::factory()->create(['name' => "Mordenkainen's Private Sanctum", 'level' => 4]);
        Spell::factory()->create(['name' => "Mordenkainen's Sword", 'level' => 7]);
        Spell::factory()->create(['name' => "Move Earth", 'level' => 6]);
        Spell::factory()->create(['name' => "Nondetection", 'level' => 3]);
        Spell::factory()->create(['name' => "Nystul's Magic Aura", 'level' => 2]);
        Spell::factory()->create(['name' => "Otiluke's Freezing Sphere", 'level' => 6]);
        Spell::factory()->create(['name' => "Otiluke's Resilient Sphere", 'level' => 4]);
        Spell::factory()->create(['name' => "Otto's Irresistible Dance", 'level' => 6]);
        Spell::factory()->create(['name' => "Pass without Trace", 'level' => 2]);
        Spell::factory()->create(['name' => "Passwall", 'level' => 5]);
        Spell::factory()->create(['name' => "Phantasmal Force", 'level' => 2]);
        Spell::factory()->create(['name' => "Phantasmal Killer", 'level' => 4]);
        Spell::factory()->create(['name' => "Phantom Steed", 'level' => 3]);
        Spell::factory()->create(['name' => "Planar Ally", 'level' => 6]);
        Spell::factory()->create(['name' => "Planar Binding", 'level' => 5]);
        Spell::factory()->create(['name' => "Plane Shift", 'level' => 7]);
        Spell::factory()->create(['name' => "Plant Growth", 'level' => 3]);
        Spell::factory()->create(['name' => "Poison Spray", 'level' => 0]);
        Spell::factory()->create(['name' => "Polymorph", 'level' => 4]);
        Spell::factory()->create(['name' => "Power Word Fortify", 'level' => 7]);
        Spell::factory()->create(['name' => "Power Word Heal", 'level' => 9]);
        Spell::factory()->create(['name' => "Power Word Kill", 'level' => 9]);
        Spell::factory()->create(['name' => "Power Word Stun", 'level' => 8]);
        Spell::factory()->create(['name' => "Prayer of Healing", 'level' => 2]);
        Spell::factory()->create(['name' => "Prestidigitation", 'level' => 0]);
        Spell::factory()->create(['name' => "Prismatic Spray", 'level' => 7]);
        Spell::factory()->create(['name' => "Otherworldly Steed", 'level' => 3]);
        Spell::factory()->create(['name' => "Prismatic Wall", 'level' => 9]);
        Spell::factory()->create(['name' => "Produce Flame", 'level' => 0]);
        Spell::factory()->create(['name' => "Programmed Illusion", 'level' => 6]);
        Spell::factory()->create(['name' => "Project Image", 'level' => 7]);
        Spell::factory()->create(['name' => "Protection from Energy", 'level' => 3]);
        Spell::factory()->create(['name' => "Protection from Evil and Good", 'level' => 1]);
        Spell::factory()->create(['name' => "Protection from Poison", 'level' => 2]);
        Spell::factory()->create(['name' => "Purify Food and Drink", 'level' => 1]);
        Spell::factory()->create(['name' => "Raise Dead", 'level' => 5]);
        Spell::factory()->create(['name' => "Rary's Telepathic Bond", 'level' => 5]);
        Spell::factory()->create(['name' => "Ray of Enfeeblement", 'level' => 2]);
        Spell::factory()->create(['name' => "Ray of Frost", 'level' => 0]);
        Spell::factory()->create(['name' => "Ray of Sickness", 'level' => 1]);
        Spell::factory()->create(['name' => "Regenerate", 'level' => 7]);
        Spell::factory()->create(['name' => "Reincarnate", 'level' => 5]);
        Spell::factory()->create(['name' => "Remove Curse", 'level' => 3]);
        Spell::factory()->create(['name' => "Resistance", 'level' => 0]);
        Spell::factory()->create(['name' => "Resurrection", 'level' => 7]);
        Spell::factory()->create(['name' => "Reverse Gravity", 'level' => 7]);
        Spell::factory()->create(['name' => "Revivify", 'level' => 3]);
        Spell::factory()->create(['name' => "Rope Trick", 'level' => 2]);
        Spell::factory()->create(['name' => "Sacred Flame", 'level' => 0]);
        Spell::factory()->create(['name' => "Sanctuary", 'level' => 1]);
        Spell::factory()->create(['name' => "Scorching Ray", 'level' => 2]);
        Spell::factory()->create(['name' => "Scrying", 'level' => 5]);
        Spell::factory()->create(['name' => "Searing Smite", 'level' => 1]);
        Spell::factory()->create(['name' => "See Invisibility", 'level' => 2]);
        Spell::factory()->create(['name' => "Seeming", 'level' => 5]);
        Spell::factory()->create(['name' => "Sending", 'level' => 3]);
        Spell::factory()->create(['name' => "Sequester", 'level' => 7]);
        Spell::factory()->create(['name' => "Shapechange", 'level' => 9]);
        Spell::factory()->create(['name' => "Shatter", 'level' => 2]);
        Spell::factory()->create(['name' => "Shield", 'level' => 1]);
        Spell::factory()->create(['name' => "Shield of Faith", 'level' => 1]);
        Spell::factory()->create(['name' => "Shillelagh", 'level' => 0]);
        Spell::factory()->create(['name' => "Shining Smite", 'level' => 2]);
        Spell::factory()->create(['name' => "Shocking Grasp", 'level' => 0]);
        Spell::factory()->create(['name' => "Silence", 'level' => 2]);
        Spell::factory()->create(['name' => "Silent Image", 'level' => 1]);
        Spell::factory()->create(['name' => "Simulacrum", 'level' => 7]);
        Spell::factory()->create(['name' => "Sleep", 'level' => 1]);
        Spell::factory()->create(['name' => "Sleet Storm", 'level' => 3]);
        Spell::factory()->create(['name' => "Slow", 'level' => 3]);
        Spell::factory()->create(['name' => "Sorcerous Burst", 'level' => 0]);
        Spell::factory()->create(['name' => "Spare the Dying", 'level' => 0]);
        Spell::factory()->create(['name' => "Speak with Animals", 'level' => 1]);
        Spell::factory()->create(['name' => "Speak with Dead", 'level' => 3]);
        Spell::factory()->create(['name' => "Speak with Plants", 'level' => 3]);
        Spell::factory()->create(['name' => "Spider Climb", 'level' => 2]);
        Spell::factory()->create(['name' => "Spike Growth", 'level' => 2]);
        Spell::factory()->create(['name' => "Spirit Guardians", 'level' => 3]);
        Spell::factory()->create(['name' => "Spiritual Weapon", 'level' => 2]);
        Spell::factory()->create(['name' => "Staggering Smite", 'level' => 4]);
        Spell::factory()->create(['name' => "Starry Wisp", 'level' => 0]);
        Spell::factory()->create(['name' => "Steel Wind Strike", 'level' => 5]);
        Spell::factory()->create(['name' => "Stinking Cloud", 'level' => 3]);
        Spell::factory()->create(['name' => "Stone Shape", 'level' => 4]);
        Spell::factory()->create(['name' => "Stoneskin", 'level' => 4]);
        Spell::factory()->create(['name' => "Storm of Vengeance", 'level' => 9]);
        Spell::factory()->create(['name' => "Suggestion", 'level' => 2]);
        Spell::factory()->create(['name' => "Summon Aberration", 'level' => 4]);
        Spell::factory()->create(['name' => "Summon Beast", 'level' => 2]);
        Spell::factory()->create(['name' => "Summon Celestial", 'level' => 5]);
        Spell::factory()->create(['name' => "Summon Construct", 'level' => 4]);
        Spell::factory()->create(['name' => "Summon Dragon", 'level' => 5]);
        Spell::factory()->create(['name' => "Summon Elemental", 'level' => 4]);
        Spell::factory()->create(['name' => "Summon Fey", 'level' => 3]);
        Spell::factory()->create(['name' => "Summon Fiend", 'level' => 6]);
        Spell::factory()->create(['name' => "Summon Undead", 'level' => 3]);
        Spell::factory()->create(['name' => "Sunbeam", 'level' => 6]);
        Spell::factory()->create(['name' => "Sunburst", 'level' => 8]);
        Spell::factory()->create(['name' => "Swift Quiver", 'level' => 5]);
        Spell::factory()->create(['name' => "Symbol", 'level' => 7]);
        Spell::factory()->create(['name' => "Synaptic Static", 'level' => 5]);
        Spell::factory()->create(['name' => "Tasha's Bubbling Cauldron", 'level' => 6]);
        Spell::factory()->create(['name' => "Tasha's Hideous Laughter", 'level' => 1]);
        Spell::factory()->create(['name' => "Telekinesis", 'level' => 5]);
        Spell::factory()->create(['name' => "Telepathy", 'level' => 8]);
        Spell::factory()->create(['name' => "Teleport", 'level' => 7]);
        Spell::factory()->create(['name' => "Teleportation Circle", 'level' => 5]);
        Spell::factory()->create(['name' => "Tenser's Floating Disk", 'level' => 1]);
        Spell::factory()->create(['name' => "Thaumaturgy", 'level' => 0]);
        Spell::factory()->create(['name' => "Thorn Whip", 'level' => 0]);
        Spell::factory()->create(['name' => "Thunderclap", 'level' => 0]);
        Spell::factory()->create(['name' => "Thunderous Smite", 'level' => 1]);
        Spell::factory()->create(['name' => "Thunderwave", 'level' => 1]);
        Spell::factory()->create(['name' => "Time Stop", 'level' => 9]);
        Spell::factory()->create(['name' => "Toll the Dead", 'level' => 0]);
        Spell::factory()->create(['name' => "Tongues", 'level' => 3]);
        Spell::factory()->create(['name' => "Transport via Plants", 'level' => 6]);
        Spell::factory()->create(['name' => "Tree Stride", 'level' => 5]);
        Spell::factory()->create(['name' => "True Polymorph", 'level' => 9]);
        Spell::factory()->create(['name' => "True Resurrection", 'level' => 9]);
        Spell::factory()->create(['name' => "True Seeing", 'level' => 6]);
        Spell::factory()->create(['name' => "True Strike", 'level' => 0]);
        Spell::factory()->create(['name' => "Tsunami", 'level' => 8]);
        Spell::factory()->create(['name' => "Unseen Servant", 'level' => 1]);
        Spell::factory()->create(['name' => "Vampiric Touch", 'level' => 3]);
        Spell::factory()->create(['name' => "Vicious Mockery", 'level' => 0]);
        Spell::factory()->create(['name' => "Vitriolic Sphere", 'level' => 4]);
        Spell::factory()->create(['name' => "Wall of Fire", 'level' => 4]);
        Spell::factory()->create(['name' => "Wall of Force", 'level' => 5]);
        Spell::factory()->create(['name' => "Wall of Ice", 'level' => 6]);
        Spell::factory()->create(['name' => "Wall of Stone", 'level' => 5]);
        Spell::factory()->create(['name' => "Wall of Thorns", 'level' => 6]);
        Spell::factory()->create(['name' => "Warding Bond", 'level' => 2]);
        Spell::factory()->create(['name' => "Water Breathing", 'level' => 3]);
        Spell::factory()->create(['name' => "Water Walk", 'level' => 3]);
        Spell::factory()->create(['name' => "Web", 'level' => 2]);
        Spell::factory()->create(['name' => "Weird", 'level' => 9]);
        Spell::factory()->create(['name' => "Wind Wall", 'level' => 3]);
        Spell::factory()->create(['name' => "Wish", 'level' => 9]);
        Spell::factory()->create(['name' => "Witch Bolt", 'level' => 1]);
        Spell::factory()->create(['name' => "Word of Radiance", 'level' => 0]);
        Spell::factory()->create(['name' => "Word of Recall", 'level' => 6]);
        Spell::factory()->create(['name' => "Wrathful Smite", 'level' => 1]);
        Spell::factory()->create(['name' => "Yolande's Regal Presence", 'level' => 5]);
        Spell::factory()->create(['name' => "Zone of Truth", 'level' => 2]);
    }
}
